# Nom du workflow
name: .NET CI

# Déclencheurs : sur push et pull request sur la branche main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Jobs à exécuter
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Installer .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurer les dépendances
      run: dotnet restore

    - name: Construire le projet
      run: dotnet build --no-restore --configuration Release

    - name: Lancer les tests
      run: dotnet test --no-build --verbosity normal
